name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次检查
  workflow_dispatch: # 允许你在网页上手动点击运行

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    permissions:
      contents: write # <--- 加上这一行，赋予插件在仓库里写入空提交的权限
    steps:
      - uses: actions/checkout@v4
      
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
